Change from clients.openWindow to event.openWindow.
w3c/webpayments-payment-apps-api pull request #106
Opened 2017-03-14 14:50 UTC by tommythorsen

This change introduces a new method on the PaymentRequestEvent, called
openWindow(). It is similar to clients.openWindow, but since it has a
tighter relationship to the PaymentRequest, it should be more convenient
for implementors to provide an experience that fits the payment flow.

See https://github.com/w3c/webpayments-payment-apps-api/issues/97.

2017-03-14 15:31 UTC, adrianhopebailie approved these changes
LGTM, thanks @tommythorsen

2017-03-15 08:33 UTC, tommythorsen commented
I have updated the PR to sit on top of @ianbjacobs' restructuring. Does it still look ok?

2017-03-15 08:39 UTC, marcoscaceres requested changes

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +        Promise<WindowClient> openWindow(DOMString url);
URL are USVStrings

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +        <dt><code>openWindow</code> method</dt>
Please define methods in their own section.

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +          the user.
Should like to algorithm that describes steps

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +  <p>A payment handler that requires visual display and user interaction, may call <code>PaymentRequestEvent.openWindow()</code>.
nit: `<code>PaymentRequestEvent.openWindow()</code>.` <a>openWindow()</a>`.

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +    A single <a>payment handler</a> SHOULD NOT be allowed to open more than one client window using this method.
All this needs to be in algorithm.

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +    The exact behavior in the case where a payment handler calls <code>openWindow()</code> multiple times, is left to the user agent implementers to decide on.
It should probably throw.

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +    The exact behavior in the case where a payment handler calls <code>openWindow()</code> multiple times, is left to the user agent implementers to decide on.
(invalid state error)

2017-03-15 08:39 UTC, marcoscaceres commented on index.html
> +  <p>User agents SHOULD display the origin of the payment handler to the user.</p>
Should be in the privacy and security considerations section

2017-03-15 08:50 UTC, marcoscaceres commented
This is not aimed at @tommythorsen - but in general, can we please be extremely disciplined with adding things to this spec. 

We've had to waste a lot of time on the Payment Request spec dealing with technical debt built up by adding bad markup, random phrasing, conformance statements that don't actually apply to any products, etc. 

Can we also be disciplined with running [HTML5 Tidy](https://github.com/htacg/tidy-html5) over the document before any commit goes in - and make sure ReSpec is being utilized to the fullest (i.e., don't use `<code>` tags). And make sure we don't pollute the commit history with random commit messages. 

Also, no one should be committing directly to `gh-pages`. @sideshowbarker, can you please set up branch protection to stop people doing that - i.e., only allow pull requests? 

ReSpec is already screaming that this document has over 66 issues. That's already really alarming - we need to do better and not rush things into the spec. 

If Editors need a "how to best use ReSpec" tutorial during the F2F, I'm happy to run that.

2017-03-15 09:37 UTC, sideshowbarker commented
> no one should be committing directly to `gh-pages`. @sideshowbarker, can you please set up branch protection to stop people doing that - i.e., only allow pull requests?

I doesn’t seem appropriate for me or anybody else from the W3C staff to try to unilaterally impose branch protection on a repo. That should be something for the people actually doing the work to discuss and decide on. https://github.com/orgs/w3c/teams/payment-app-api-editors shows a number of people with admin access to the repo who can set pull-request-required branch protection for the default branch if that’s what they want.

2017-03-15 09:38 UTC, marcoscaceres commented
@sideshowbarker, fair. Can someone with admin please put branch protection on?

2017-03-15 09:54 UTC, tommythorsen commented on index.html
> +        Promise<WindowClient> openWindow(DOMString url);
From https://heycam.github.io/webidl/#idl-USVString:
> Specifications should only use USVString for APIs that perform text processing and need a string of Unicode scalar values to operate on. Most APIs that use strings should instead be using DOMString, which does not make any interpretations of the code units in the string. When in doubt, use DOMString.

I was in doubt, so I used DOMString. What calls for USVString in this situation?

2017-03-15 10:30 UTC, tommythorsen commented
@marcoscaceres 
> Can someone with admin please put branch protection on?

Done!

2017-03-15 10:39 UTC, tommythorsen commented on index.html
> +        <dt><code>openWindow</code> method</dt>
I've done this, but now this section is inconsistent with the rest of the document. I can go through and give the other sections the same treatment, but that will be a separate PR.

2017-03-15 12:58 UTC, adrianhopebailie commented
> This is not aimed at @tommythorsen - but in general, can we please be extremely disciplined with adding things to this spec.

> We've had to waste a lot of time on the Payment Request spec dealing with technical debt built up by adding bad markup, random phrasing, conformance statements that don't actually apply to any products, etc.

> Can we also be disciplined with running HTML5 Tidy over the document before any commit goes in - and make sure ReSpec is being utilized to the fullest (i.e., don't use <code> tags). And make sure we don't pollute the commit history with random commit messages.

@marcoscaceres - thanks for this comment. I think I speak for all of the editors (@ianbjacobs , @adamroach , @tommythorsen , @jnormore and myself) when I say that we're fairly new to this (and if not then fairly new to specs that include WebIDL and browser algorithms or new to ReSpec or GitHub or all of it).

So, I am 100% in agreement that we try and avoid accumulating debt that we need to deal with later but also appeal to you to help us out here.

Feel free to point out things we're doing wrong (as you have above) or share some pro tips because we're keen to do them right.

While I appreciate you are putting a lot of effort into the PR spec right now your help as an editor here would be appreciated if you can spare some time. I think that at a minimum @tommythorsen , you and I could have an occasional call to sync up since timezones make it hard for you guys to join the TF calls.

2017-03-15 14:29 UTC, tommythorsen commented on index.html
> +    A single <a>payment handler</a> SHOULD NOT be allowed to open more than one client window using this method.
I'm working on this. Aiming to update this PR with an algorithm for openWindow tomorrow.

2017-03-15 14:29 UTC, tommythorsen commented on index.html
> +    The exact behavior in the case where a payment handler calls <code>openWindow()</code> multiple times, is left to the user agent implementers to decide on.
Ok. I'll change this.

2017-03-16 09:37 UTC, tommythorsen commented
I think I have addressed all of @marcoscaceres' review comments. I have introduced a few more respec warnings, but I intend to take a closer look at the whole list of respec issues in another PR, after this one is finished.

2017-03-16 11:19 UTC, marcoscaceres commented
Thanks for the update. Will follow up soon. 

> On 16 Mar 2017, at 8:37 pm, Tommy Thorsen <notifications@github.com> wrote:
> 
> I think I have addressed all of @marcoscaceres' review comments. I have introduced a few more respec warnings, but I intend to take a closer look at the whole list of respec issues in another PR, after this one is finished.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-03-16 13:09 UTC, ianbjacobs commented
Thank you @tommythorsen! I have looked at the changes. I look forward to @marcoscaceres' review. 

@jakearchibald, your input would also be appreciated.

Ian

2017-03-17 01:37 UTC, marcoscaceres commented
A general note on style and invoking algorithms: see how it's done in the Payment Request spec. Ideally, this spec should end up being edited in the same way as that one. 

For other examples of excellent specs whose style we should follow:

 * https://fetch.spec.whatwg.org
 * https://url.spec.whatwg.org

2017-03-17 04:17 UTC, dlongley commented
The general approach of opening the window via a call on the event (to make it context-aware) LGTM.

2017-03-17 04:52 UTC, marcoscaceres commented
> @marcoscaceres - thanks for this comment. I think I speak for all of the editors (@ianbjacobs , @adamroach , @tommythorsen , @jnormore and myself) when I say that we're fairly new to this (and if not then fairly new to specs that include WebIDL and browser algorithms or new to ReSpec or GitHub or all of it).

Good guides if getting started:

  * [API Design Principles](https://w3ctag.github.io/design-principles/)
  * [Writing Promise-Using Specifications](http://www.w3.org/2001/tag/doc/promises-guide)
  * [ReSpec](https://github.com/w3c/respec/wiki)
 
>So, I am 100% in agreement that we try and avoid accumulating debt that we need to deal with later but also appeal to you to help us out here.

I'm happy to help. Please tag me on reviews and I'll get to them as quickly as possible. I'll have more time once we put Payment Request into CR.

2017-03-17 09:52 UTC, tommythorsen commented
@marcoscaceres: Thanks for the pointers!

Did you have any specific change requests? This PR is blocked from merging by your earlier change request, so if you're happy with the current state of the PR, perhaps you would like to change to approval?

2017-03-17 14:28 UTC, marcoscaceres commented
Odd? I added 30+ change requests earlier today? 

> On 17 Mar 2017, at 8:52 pm, Tommy Thorsen <notifications@github.com> wrote:
> 
> @marcoscaceres: Thanks for the pointers!
> 
> Did you have any specific change requests? This PR is blocked from merging by your earlier change request, so if you're happy with the current state of the PR, perhaps you would like to change to approval?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-03-17 14:46 UTC, marcoscaceres commented
@tommythorsen see my change requests above. I can see them all there

2017-03-17 14:48 UTC, tommythorsen commented
30 change requests from today? The only change requests I can see are the 7 outdated ones from two days ago.

2017-03-20 11:52 UTC, tommythorsen commented
@marcoscaceres: I still see no new change requests from you. I have not received an email about them either. Can you double-check that they have been submitted?

Can anyone else see these new change requests? @ianbjacobs? @adrianhopebailie?

2017-03-20 13:01 UTC, marcoscaceres requested changes

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +              <th>Description (<em>non-normative</em>)</th>
If we are going to have defaults, we should have a default column in the table.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <code>PaymentRequest.show()</code> and subsequent user
Nit: `<code><a data-cite="!payment-request#show-method">PaymentRequest.show()</a></code>`

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          MUST run the following steps or their equivalent:</p>
nit: remove "their equivalent"

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +            worker registration</a> corresponding to the payment
Expected link to "payment handler" definition

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +        <p class="note">This algorithm is <i>very</i> similar to
nit: class="ednote" ... should probably file a new bug for this, then we can link it to the spec.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +        <p class="note">This algorithm is <i>very</i> similar to
See also: https://github.com/w3c/respec/wiki/Referencing-GitHub-issues-in-your-spec

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +        "https://www.w3.org/TR/service-workers/#clients-openwindow">
Nit: don't link to specs directly. instead:

```
<a data-cite="!service-workers/#clients-openwindow">Open Window Algorithm</a>
```

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +        "https://www.w3.org/TR/service-workers/#clients-openwindow">
And yes, we should do the security checks, and then defer to the the service worker algorithm.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <li>If <var>request</var>.[[\state]] is not
nit: link to `<a>[[\state]]</a>`

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          "interactive", then return a Promise rejected with a <a>
Nit: link and define "interactive"

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +            "<a>InvalidStateError</a>".
Please see: https://www.w3.org/2001/tag/doc/promises-guide with regards to phrasing of these. It's close, but could be better.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <li>Let <var>url</var> be the result of parsing the
Note, this can throw.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <li>Let <var>url</var> be the result of parsing the
Also, we should invoke the [[!WHATWG-URL]] parser here.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          rejected with a <a>TypeError</a>.
You should re-throw the error instead of creating an empty one.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +              <li>Navigate <var>newContext</var> to <var>url</var>,
Nit: link to html navigate.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +              <li>Navigate <var>newContext</var> to <var>url</var>,
Same with the exception types

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <li>Run these steps in parallel:
nit: link to in parallel

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +              <li>If the origin is not the same as the
Need to clear which origin (the origin of the newContext). Also, what happens if the newContext goes from:

```
newContext->foo.com REDIRECT newContext->bar.com REDIRECT newContext->foo.com

```

So probably need to track navigations.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                  <li>Resolve promise with null.</li>
Wonder why this doesn't reject with a SecurityError?

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                equivalent, with <var>newContext</var> as the
nit: drop "or its equivalent" (yes, I know it's in the SW spec... it's silly there too :))

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                <ol class="algorithm">
nit, I think you only need "algorithm" on the top-most `ol`

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                  <var>event</var>.<a>[[\windowClient]]</a>.visibilityState
nit: link to .visibilityState, so one can see what other states it could possibly be in.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +        <a>Promise</a>&lt;<a>WindowClient</a>&gt; openWindow(DOMString url);
This has to be a USVString. It can't be a DOMString. You can't pass a DOMString representing a URL.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +            Promise that was created by
Nit: promise should be linked or treated as a concept. In either case, it should be linked to something.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +        <a>Promise</a>&lt;<a>WindowClient</a>&gt; openWindow(DOMString url);
Don't add `a` elements inside IDL. ReSpec will do the linking for you.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +            <li>Invoke the <a>Handle Functional Event</a> algorithm
Nit: lowercase the algorithm name.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +            <code>PaymentRequest.show()</code> with a
We might want to abstract away ".show()", as in something can request request for payment, but not necessarily the Payment Request API.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                <li>Set <var>global</var> to the global object that
I'm confused, where was "global" passed?

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                <li>Create a <a>trusted event</a>, <var>e</var>,
Use WHATWG-DOM fire an event here instead of the following subsets.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +                <li>Set the <code>appRequest</code> attribute of
nit: `<code>` should be `<a>`

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +      <p>A payment handler that requires visual display and user
Wait? who is the payment handler here? User code or the browser arbitrarily calling some JS function?

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +      consistent with the flow and not confusing to the user.</p>
This whole assertion seems very wishy-washy, tbh. Maybe this should be a note?

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +      <p>The resulting window client is bound to the tab/window
Same with this... all this reads very "non-normative".

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +      <p>The <a>payment app request</a> is
this is redundant. Talk about `PaymentAppRequest` instead.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <h3><dfn data-lt="openWindow()">openWindow</dfn>
nit: `<dfn>openWindow()</dfn>`

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          window to the user. It invokes the <a>Open Window
Maybe say: "When called, it runs the ..." in lower case.

2017-03-20 13:01 UTC, marcoscaceres commented on index.html
> +          <h3><dfn>respondWith</dfn> method</h3>
nit:  missing "()"

2017-03-20 13:02 UTC, marcoscaceres commented
Argh, my bad. Seems I didn't hit the request changes button.

2017-03-21 08:43 UTC, tommythorsen commented on index.html
> +                <li>Set <var>global</var> to the global object that
I have no idea. Note that my PR does not actually write all of this. I merely put it inside a section and re-indent it, so that it looks a bit like I've written it. We can have a look at this in a different Issue/PR.

2017-03-21 08:43 UTC, tommythorsen commented on index.html
> +                <li>Create a <a>trusted event</a>, <var>e</var>,
Same as above. We can have a look at this in a different Issue/PR, since I didn't write this.

2017-03-28 03:04 UTC, marcoscaceres commented on index.html
> +                <li>Set <var>global</var> to the global object that
Sure, np.

2017-03-28 03:06 UTC, marcoscaceres approved these changes
So, approving this for merge so we can deal with the much larger issues around event dispatching. All that needs to be rewritten.

2017-03-28 03:08 UTC, marcoscaceres commented
I feel like we should still pull everything out of this spec an slowly add it back in one part at a time. We've again gone rushed a whole bunch of stuff into a spec without it being carefully checked 😭.

2017-03-29 13:32 UTC, merged