Respect fixes
w3c/webpayments-payment-apps-api pull request #126
Opened 2017-04-05 21:32 UTC by ianbjacobs

(Except 5)

2017-04-05 21:34 UTC, ianbjacobs commented
@marcoscaceres,

Unfortunately I am not that familiar with respec. Nonetheless, I endeavored to remove the errors and seem to have squashed all but 5 (by adding definitions, and sort of looking at how payment request API works under the hood). 

I would appreciate any help in squashing the final 5. After that I was doing to do a tidy pass, then more edits after that.

In this edit I also changed WalletDetails to PaymentWallet per 4 April discussion.

2017-04-06 00:05 UTC, marcoscaceres requested changes

2017-04-06 00:05 UTC, marcoscaceres commented on index.html
> +      <dd>The terms <dfn data-lt="payment method|payment methods">payment method</dfn>, <dfn>PaymentRequest</dfn>,
FYI, you don't need to double define "payment method". Same applies everywhere else.

2017-04-06 00:19 UTC, marcoscaceres requested changes

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <p>
Just reference PR spec directly here. Don't redefine it.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +      <li>When the user (the <dfn>payer</dfn>) selects an Instrument, the user agent fires the
this should link to "fire an event" (DOM spec) and needs to use the "user interaction task source" using the "PaymentRequestEvent" interface.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +    <section data-dfn-for="PaymentInstruments">
Also add `data-link-for="PaymentInstruments"` - same for other sections. Saves some work later.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +      <pre id="payment-instrument-idl" class="idl">
Please don't ID `pre` sections.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
>          <dd>The <code>name</code> member is a string that
Please replace this with an `<a>`

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <dt><dfn id="payment-instrument-enabled-methods">enabledMethods</dfn> member</dt>
Please remove this id

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <dt><dfn id="payment-instrument-enabled-methods">enabledMethods</dfn> member</dt>
Same with any other id on DFN. Let ReSpec take care of that.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <dt><dfn id="payment-instrument-capabilities">capabilities</dfn> member</dt>
As above.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <dd>The <code>capabilities</code>
Please avoid `code`. Let ReSpec determine what should be code or not from the dfn. Just put `<a>` here.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +                                              PaymentWallet details);
Move this to the previous line.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <dt><dfn>keys</dfn> method</dt>
Method definitions should really be in their own section - same with attributes. See PR spec. Otherwise, they don't show up in the ToC, making them difficult to find.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +              the <code>walletKey</code>s for the <a>PaymentWallet</a>s
Change code to `<a>`

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +      <h3><dfn>PaymentWallet</dfn> dictionary</h3>
BTW, seems odd that these are H3? These should really be H2... there might be a structuring problem with the spec.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +      <pre id="payment-wallet-idl" class="idl">
Remove ID.

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +        <dt><dfn id="payment-wallet-name">name</dfn> member</dt>
Remove all these ids...

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +      <code>PaymentManager</code>),
`a` here too

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +                <li>Set the <a href="#apprequest">appRequest</a> attribute of
Don't link directly to things like this. Just use `<a data-lt="PaymentAppRequest .appRequest">appRequest</a>`

2017-04-06 00:19 UTC, marcoscaceres commented on index.html
> +              <var>event</var>.<a href="#appRequest">appRequest</a>.<a href=
Same here.

2017-04-06 00:25 UTC, ianbjacobs commented
Thanks for the review, @marcoscaceres. Respec by fire!

I'll make the suggested changes (but not tonight).

Ian

2017-04-06 06:49 UTC, marcoscaceres commented
I'll try to help out soon too... must ... finish... PR ... spec....

2017-04-06 21:29 UTC, ianbjacobs commented
Hi @marcoscaceres, I made the updates you suggested (and some others). There are still three warnings. I believe that two of them may be due to a respec bug. They are:

   - <dfn> for paymentManager in ServiceWorkerRegistration. Please define it and link to spec that declares it.
   - No <dfn> for PaymentManager. Please define it and link to spec that declares it. 

One manifestation of the problem is that the section "PaymentManager interface" is not correctly formatted. If I change the "paymentManager" attribute name in the previous IDL block to "foo" the problem goes away. So this seems to be either a WebIDL issue (sorry...I am not a WebIDL pro) or a respec issue.

I have not yet tidied the text. I plan to do that next, followed by other edits. If you'd like me to tidy this pull request after you have reviewed it, I can do that.

2017-04-12 03:02 UTC, marcoscaceres requested changes
Getting there... note that I didn't review the actual content. Just mostly the markup.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +                "BASIC-CARD": {
You should remove this. Just cite "[[!payment-method-basic-card]]"

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <dd>The terms <dfn>payment method</dfn>, <dfn>PaymentRequest</dfn>,
all this need to be referenced as (see how I did it in the PR spec):

```HTML
<dfn data-cite="!PAYMENT-REQUEST-API#payment-method">payment method</dfn>
```

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      API specification [[!PAYMENT-REQUEST-API]]. This specification also relies on the Payment Request API usage of <dfn>Promise</dfn>, <dfn>internal slot</dfn>, <dfn>TypeError</dfn>, <dfn>JSON.stri
This is not correct: 

> This specification also relies on the Payment Request API usage of <dfn>Promise</dfn>

Promise comes from the ES6 spec.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      API specification [[!PAYMENT-REQUEST-API]]. This specification also relies on the Payment Request API usage of <dfn>Promise</dfn>, <dfn>internal slot</dfn>, <dfn>TypeError</dfn>, <dfn>JSON.stri
(same with other terms here... again, you can probably just copy/paste from the PR spec.)

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <dd>The terms <dfn data-lt="payment method identifier|payment method identifiers">payment method identifier</dfn> is defined by the Payment Method
Nit: you don't need "payment method identifier"... the original term is derived from the `dfn`... so just:

```
<dfn data-lt="payment method identifiers">payment method identifier</dfn>
```

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <dd>The terms <dfn>basic-card</dfn>, <dfn>supportedNetworks</dfn>, and <dfn>supportedTypes</dfn> are defined in [[BASIC-CARD]].</dd>
Nit: shouldn't [[BASIC-CARD]] be normatively referenced? As in [[!BASIC-CARD]]

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <dd>The terms <dfn>global object</dfn>, <dfn>origin</dfn>,
Nit: origin is defined in the origin spec.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +            <td><dfn>AbortError</dfn></td>
These are all defined in WebIDL - not in DOM.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +            <td><dfn>AbortError</dfn></td>
(you can copy/paste this also from PR spec... but please don't define terms that are not used!)

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +            <td><dfn>NotAllowedError</dfn></td>
Please remove the table. See how we do it in PR spec.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <dd>The terms <dfn>service worker</dfn>, <dfn>ServiceWorkerRegistration</dfn>, <dfn>ServiceWorkerGlobalScope</dfn>, <dfn>handle functional event</dfn>, <dfn>extend lifetime promises</dfn>, and
As above... For cited interfaces, please use:

```HTML
<code><dfn>ServiceWorkerGlobalScope</dfn></code>
```

ReSpec will automatically "code" all cross referenced for you.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <li>When the merchant (or other <dfn>payee</dfn>) calls Payment Request API (e.g., when
Nit: please `<cite>` Payment Request API - or better yet, link to it.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +    <h2><dfn>Payment Handler</dfn> Registration</h2>
Nit, this seems like an odd place to dfn "Payment Handler" - specially if this is to do with registration.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <h2>Extension to the ServiceWorkerRegistration interface</h2>
Nit: `<code>ServiceWorkerRegistration</code>`

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <pre class="example highlight" title="Removing all instruments">
Nit: you don't need "highlight" in the class list - you might just want to say "js".

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +        return paymentManager.instruments.keys().then((keys) =&gt; {
This example doesn't make any sense... it's both a syntax error and doesn't do anything with `Promise.all`. 

If we want to `clear()`, then we should add a clear method to the interface.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +          Promise&lt;void&gt;              set(DOMString instrumentKey, PaymentInstrument details);
See below. Let's just add:
```
Promise&lt;void&gt;              clear();
```

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <p>Where it appears, The <dfn>walletKey</dfn> parameter is
s/parameter/argument?

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <p>Where it appears, The <dfn>walletKey</dfn> parameter is
Actually, check what IDL uses... I can't remember if it is "parameter" or "argument" or something else.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +        <h2><dfn>delete</dfn> method</h2>
nit: please change to `<dfn>delete()</dfn>` ... and please do the same for other methods.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +              with a matching <a>walletKey</a>, remove it from
nit: arguments should be marked up using `<var>`

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +              the <a>walletKey</a>s for the <a>PaymentWallet</a>s
This should say something about the ordering of the collection.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
>      <section id="register-example">
This section should probably be marked as non-normative.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +			       "https://tools.ietf.org/html/rfc6454#section-6.1">Unicode
please don't cite specs using URLs... just [[!rfc6454#section-6.1]].

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +			       "https://tools.ietf.org/html/rfc6454#section-6.1">Unicode
fixed comment above.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      self.addEventListener('paymentrequest', function(e) {
Please remove this example - it's no good. Sorry :(

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      self.addEventListener('paymentrequest', function(e) {
Please move it to another bug, and I'll try to rewrite it. But it contains a bunch of bugs and just outright "oh god no!" 😱.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +              reject(e.data);
😱

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      self.addEventListener('paymentrequest', function(e) {
I'll convert it to use async syntax... will be much more legible. Remember the rule: if you see `.then()` anywhere, that's a code smell and likely an anti-pattern.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +            if (e.data.hasOwnProperty('name')) {
... also, if async code nests more than 3 levels, that's also indicative that something is wrong.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <pre class="example highlight" title=
Nit: s/highlight/html 

This should be a:

```HTML 
<form>
  <label>Cardholder Name: <input ... ></label>
</form>
```

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <pre class="example highlight" title=
By "this" I mean the table below in the example.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +      <pre class="example highlight" title=
Feel free to remove and assign to me to add. 

also, please remove the html and body tags.

2017-04-12 03:02 UTC, marcoscaceres commented on index.html
> +    e.source.postMessage(paymentAppResponse);
Fire and forget? Shouldn't you wait for an ack from the other side?

2017-04-12 23:17 UTC, ianbjacobs commented
Hi @marcoscaceres, 

I made changes to address your helpful comments. Some of the changes were made
through conversation with @adamroach. Can we merge this PR? 

Once we do, I'll do a tidy pass.

Thanks!

Ian

2017-04-13 01:52 UTC, marcoscaceres approved these changes
🚢 Ship it!

2017-04-13 01:54 UTC, marcoscaceres commented
(kindly please do a squash merge - and make the message "chore: clean up markup and xrefs")

2017-04-13 01:57 UTC, marcoscaceres commented on index.html
> +          Promise&lt;void&gt;              set(DOMString instrumentKey, PaymentInstrument details);
Added https://github.com/w3c/webpayments-payment-apps-api/issues/129

2017-04-13 12:23 UTC, merged