Add a constructor of PaymentRequestEvent and PaymentRequestEventInit.
w3c/webpayments-payment-apps-api pull request #162
Opened 2017-05-23 10:34 UTC by romandev

Need the constructor and init dictionary for compatibility with DOM events.

Here are some examples:
  https://www.w3.org/TR/push-api/#pushevent-interface
  https://wicg.github.io/BackgroundSync/spec/#sync-event
  https://notifications.spec.whatwg.org/#dom-notificationevent-notificationevent

2017-05-23 10:35 UTC, romandev commented
@marcoscaceres Please take a look.

2017-05-24 08:13 UTC, marcoscaceres requested changes
Looking good...

2017-05-24 08:13 UTC, marcoscaceres commented on index.html
> +          DOMString topLevelOrigin;
Here you want: USVString (because it's a URL)

2017-05-24 08:13 UTC, marcoscaceres commented on index.html
> +          DOMString paymentRequestOrigin;
Same here as above.

2017-05-24 08:13 UTC, marcoscaceres commented on index.html
> +        };
You will need to define the things in PaymentRequestEventInit as sharing a definition with PaymentRequestEvent, or ReSpec will probably get upset.

2017-05-28 16:00 UTC, romandev reviewed
Thank you for review!

2017-05-28 16:00 UTC, romandev commented on index.html
> +          DOMString topLevelOrigin;
Done.

2017-05-28 16:00 UTC, romandev commented on index.html
> +          DOMString paymentRequestOrigin;
Done.

2017-05-28 16:00 UTC, romandev commented on index.html
> +        };
I tried to find a way to define the things in PaymentRequestEventInit as sharing a definition with PaymentRequestEvent but I couldn't.
I read WebIDL Guide[1] in respec's wiki but I couldn't find solution there.

So, I added "no-link-warnings" to the class attr of `<pre class="idl">` to silence the warnings according to your comment in [2].

If  you have another idea, please let me know.

Thank you for review!

[1] https://github.com/w3c/respec/wiki/WebIDL-Guide
[2] https://github.com/w3c/respec/issues/1027

2017-05-29 00:42 UTC, marcoscaceres commented on index.html
> +        <pre class="idl no-link-warnings">
I'd prefer we don't do this. It sets a bad precedence and doesn't address the problem. I'll provide you with a solution below.

2017-05-29 00:50 UTC, marcoscaceres requested changes

2017-05-29 00:50 UTC, marcoscaceres commented on index.html
> +        };
Try: 

```
<p>
  The <dfn>topLevelOrigin</dfn>, <dfn>paymentRequestOrigin</dfn>, <dfn>paymentRequestId</dfn>, <dfn> methodData</dfn>, <dfn>total</dfn>, <dfn> modifiers</dfn>, and <dfn>instrumentKey</dfn> members share their definitions with those defined for <a>PaymentRequestEvent</a>
</p>
```

Also, don't include `PaymentRequestEventInit` in the same `<pre>` block. Move it to its own `pre` and `section` - otherwise, it won't appear in the TOC.

2017-05-29 09:10 UTC, romandev commented on index.html
> +        <pre class="idl no-link-warnings">
Done.

Thank you for your guidance!

2017-05-31 00:01 UTC, romandev commented
Gentle ping :-)

2017-05-31 00:06 UTC, marcoscaceres commented on index.html
> +            <dfn>paymentRequestId</dfn>, <dfn> methodData</dfn>,
Nit: please run HTML5 Tidy over the doc.

2017-05-31 00:08 UTC, marcoscaceres approved these changes
Approved. Please fix the last few nits then we can merge! ❤️

2017-05-31 00:08 UTC, marcoscaceres commented on index.html
> +          <p>
Please move this paragraph underneath the WebIDL

2017-05-31 00:58 UTC, romandev reviewed
Thank you for review. I addressed your comments :)
But I have a question. The Tidy makes another change which is not related this change's context.
Is it no problem?

2017-05-31 00:58 UTC, romandev commented on index.html
> +          <p>
Done.

2017-05-31 00:58 UTC, romandev commented on index.html
> +            <dfn>paymentRequestId</dfn>, <dfn> methodData</dfn>,
I did but it contains another changes which not related this change. Is it no problem?

2017-05-31 01:02 UTC, marcoscaceres commented
Hmm... seems someone forgot to tidy the document previously which is making this PR messy :( I sent a PR for that:  https://github.com/w3c/payment-handler/pull/162

Once that goes in, we will need to rebase this one.

2017-05-31 01:03 UTC, marcoscaceres commented
@romandev, also, when you ran tidy, did you do?:

```
tidy -config tidyconfig.txt -o index.html index.html
```

I'm seeing some unexpected changes? do you have version 5.4.0?

2017-05-31 01:04 UTC, marcoscaceres requested changes
Blocking again pending other PR. Sorry for the boring procedural stuff. Text is good tho.

2017-05-31 14:01 UTC, romandev commented
@marcoscaceres 
Thank you for guide! I applied tidy and uploaded final patch set.

PTAL

2017-06-01 04:26 UTC, marcoscaceres approved these changes

2017-06-01 04:27 UTC, merged