Add ImageObject dictionary.
w3c/webpayments-payment-apps-api pull request #174
Opened 2017-06-08 10:41 UTC by romandev

The paymentinstrument and the paymentwallet have a sequence of ImageObject
as member, but there is no definition of ImageObject in the current spec.
We already know implicitly that is is similar to the image object in the
manifest spec[1]. But the does not have WebIDL definition of it, so it is
difficult to represent our data structure. To resolve the issue, this change
is adding ImageObject dictionary in WebIDL level.

2017-06-08 10:47 UTC, romandev commented
@ianbjacobs, @rsolomakhin PTAL

There has been no definition until now. So, it hasn't been easy to implement the icon fetcher in browser side.

2017-06-08 18:38 UTC, ianbjacobs commented
This relates to issue 125
https://github.com/w3c/payment-handler/issues/125

I have been wondering how much of manifest to pull in. It looks like you've taken the approach of having a bit inline, but also references to manifest (for fetching) and HTML (for some aspects of size information). I'd love to hear from other developers familiar with those specs if you like this balance.

Per Marcos' suggestion, @rsolomakhin (or another implementer), please review. Thanks!
Ian



Ian

2017-06-08 18:41 UTC, rsolomakhin commented on index.html
> +                <var>details</var> is present, then for each <var>icon</var> in
We should download the best icon for our use case, not all of them :-)

2017-06-08 18:42 UTC, rsolomakhin commented on index.html
> +            </li>
Let's require the URL of the icon to be from a secure origin. (SecureContext)

2017-06-08 18:44 UTC, rsolomakhin commented on index.html
> +            </li>
I suggest we prohibit relative URLs, because it's not clear how to resolve these into absolute URLs in the context of a service worker.

2017-06-08 18:45 UTC, rsolomakhin requested changes
Great work! A few comments inline.

2017-06-09 18:51 UTC, romandev commented on index.html
> +            </li>
IMHO, we can use relative URLs.

I added parsing step for it as follows:

>  parsing image.src with the context object's relevant settings object's API base URL.

2017-06-09 18:52 UTC, romandev commented
@rsolomakhin, @ianbjacobs Thank you for review.
I addressed your comments. PTAL

2017-06-09 18:54 UTC, rsolomakhin commented on index.html
> +            </li>
What is "the context object's relevant settings object's API base URL"? Is the the "scope" of the service worker or the path of the service worker's JavaScript file or something else entirely?

2017-06-09 19:35 UTC, romandev commented on index.html
> +            </li>
@rsolomakhin,

In a case of SW, it will be script_url.
If the script_url is https://example.com/abcd/sw.js, then:
```
// SW context
clients.openWindow('/test1.html');      // https://example.com/test1.html
clients.openWindow('../test2.html');    // https://example.com/test2.html
clients.openWindow('./test3.html');     // https://example.com/abcd/test3.html
```

In a case of document, it will be document_url.
If the document_url is https://example.com/hello/world/test.html, then:
```
// Window global context
navigator.serviceWorker.register('/test1.js');     // https://example.com/test1.js
navigator.serviceWorker.register('../test2.js');   // https://example.com/hello/test2.js
navigator.serviceWorker.register('./test3.js');    // https://example.com/hello/world/test3.js
```

The existing SW APIs already uses the processing. [1][2]

[1] https://w3c.github.io/ServiceWorker/#clients-openwindow
[2] https://w3c.github.io/ServiceWorker/#navigator-service-worker-register

2017-06-12 15:56 UTC, ianbjacobs commented on index.html
> +            </li>
@romandev, thank you for the examples. One question: given this specification's reliance on service workers, is that the only context that will be relevant here? And if so, should we say that clearly in the bullet that talks about the origin of the base URL?

Ian

2017-06-13 15:09 UTC, romandev commented on index.html
> +            </li>
@ianbjacobs,

Sorry for delayed reply. I missed this comment.
IMHO, the following parsing step is enough to explain how the relative url should be resolved clearly.
 
> parsing image.src with the context object's relevant settings object's API base URL.
 
The ImageObject is used during PaymentInstrument.set().
BTW, the PaymentInstrument is an extension of ServiceWorkerRegistration.
So, we can access it in both of window global context and worker context but only need to consider which context the API is running on.

**"the context object's relevant settings object's API base URL"**

It means that..
If the top level window, then the base url is window's location url without filename.
If it is an iframe, then the base url is iframe's url without filename.
If it is a worker, then the base url is script_url without filename.

For example, we can run PaymentInstrument.set() in window global context.
```
<script>
// https://www.example.com/abcd/test.html
navigator.seviceWorker.register(...)
    ...
    .then(registration) {
        registration.paymentManager.paymentInstrument.set({
            name: "Test Pay",
            icons: {
                src: '../icon.png'    /* https://www.example.com/icon.png */
            }
        });
    }
</script>
```

If its context is iframe, no problems.
```
<!-- https://www.example.com/abcd/efgh/index.html -->
<iframe src="https://www.example.com/abcd/efgh/iframe.html"></iframe>
```
```
<script>
// This is an iframe: https://www.example.com/abcd/efgh/iframe.html
navigator.seviceWorker.register(...)
    ...
    .then(registration) {
        registration.paymentManager.paymentInstrument.set({
            name: "Test Pay",
            icons: {
                src: '../icon.png'    /* https://www.example.com/abcd/icon.png */
            }
        });
    }
</script>
```

In a case of worker context,
```
// https://www.example.com/abcd/efgh/sw/pay.js
registration.paymentManager.paymentInstrument.set({
    name: "Test Pay",
    icons: {
        src: '../icon.png'    /* https://www.example.com/abcd/efgh/icon.png */
    }
});
```

2017-06-13 20:47 UTC, ianbjacobs commented on index.html
> +            </li>
Thanks very much, @romandev. What do you think of adding those examples after the algorithm in the section "Convert image objects" to show how relative URL conversion would happen in different contexts?

In other words: the normative text may well suffice, but the examples could help explain expected behavior in different scenarios.

2017-06-14 16:32 UTC, romandev commented on index.html
> +            </li>
@ianbjacobs Thank you for guide. I added two examples. Could you check my update?

2017-06-14 22:41 UTC, ianbjacobs commented
@rsolomakhin, my most recent suggestions are editorial. Could you please review the full PR (including example) and let us know if it looks ok. Seems like we are close to being able to merge the PR. Thanks!

Ian

2017-06-14 23:14 UTC, romandev commented
FYI, I've just fixed @ianbjacobs's comments in the latest patch. :-)
Thanks!

2017-06-15 00:21 UTC, rsolomakhin commented on index.html
> +                    </li>
Nit: remove this UX guidance. It's not important for compatibility.

2017-06-15 00:21 UTC, rsolomakhin commented on index.html
> +                    image.
Ditto.

2017-06-15 00:22 UTC, rsolomakhin commented on index.html
> +          the user agent must runs the following steps:
s/runs/run

2017-06-15 00:23 UTC, rsolomakhin commented on index.html
> +                scheme</a> is not one of "http" and "https", then return an
Let's allow only HTTPS. Using HTTP is recipe for trouble in payments world.

2017-06-15 00:24 UTC, rsolomakhin requested changes
Please prohibit usage of HTTP scheme for icon storage.

2017-06-15 11:02 UTC, rsolomakhin approved these changes

2017-06-15 12:36 UTC, merged