The PaymentRequestEvent.total attribute should be |any| type.
w3c/webpayments-payment-apps-api pull request #177
Opened 2017-06-11 14:55 UTC by romandev

The |total| attribute is currently defined as PaymentItem dictionary but
WebIDL spec says that attributes should not be a dictionary[1].
This change is fixing #175 issue.

[1] https://heycam.github.io/webidl/#idl-dictionaries

2017-06-11 14:57 UTC, romandev commented
@ianbjacobs, @rsolomakhin PTAL

2017-06-12 16:27 UTC, rsolomakhin requested changes

2017-06-12 16:27 UTC, rsolomakhin commented on index.html
> +          readonly attribute any total;
Can we use `object` type to match `data` attribute in `PaymentMethodData`?

https://w3c.github.io/browser-payment-api/#paymentmethoddata-dictionary

2017-06-12 17:25 UTC, rsolomakhin approved these changes

2017-06-12 17:25 UTC, romandev commented on index.html
> +          readonly attribute any total;
Done! Thanks.

2017-06-12 17:26 UTC, merged