Define requestPermission() behavior.
w3c/webpayments-payment-apps-api pull request #180
Opened 2017-06-21 12:40 UTC by romandev

In the current spec, there is no definition of the requestPermission() method.
This change is fixing #94 issue.

2017-06-21 12:41 UTC, romandev commented
@ianbjacobs, @rsolomakhin PTAL

Thank you.

2017-06-21 14:06 UTC, rsolomakhin commented on index.html
> +        [Exposed=Window] static Promise&lt;PermisionState&gt; requestPermission();
What does  `[Exposed=Window]` do?

2017-06-21 14:09 UTC, rsolomakhin commented on index.html
> +                "granted", and "denied" otherwise.
Your [implementation](https://codereview.chromium.org/2946013002/diff/1/third_party/WebKit/Source/modules/payments/PaymentManager.cpp) can also resolve `p` with `"default"`. When would that happen?

2017-06-21 14:10 UTC, rsolomakhin commented on index.html
> +            <a>Promise</a> rejected with a <a>SecurityError</a>.
`NotAllowedError` might be better, IMHO.

2017-06-21 14:10 UTC, rsolomakhin commented on index.html
> +            <a>Promise</a> rejected with a <a>SecurityError</a>.
Ditto

2017-06-21 14:12 UTC, rsolomakhin requested changes
Thank you for the patch! Good work!

2017-06-21 14:23 UTC, dlongley commented on index.html
> +        [Exposed=Window] static Promise&lt;PermisionState&gt; requestPermission();
I believe that the `[SecureContext]` extended attribute applies to the entire interface (exposing it only in secure contexts) and the `[Exposed=Window]` is a further restriction, specifically, on `requestPermission` to cause it to only be exposed when the global context is `Window` (as opposed to in a `Worker`, for example -- where it won't be accessible).

2017-06-21 14:23 UTC, dlongley commented on index.html
> +        [Exposed=Window] static Promise&lt;PermisionState&gt; requestPermission();
Also, there's a typo here: `PermisionState` => `PermissionState`

2017-06-21 14:30 UTC, dlongley commented on index.html
> +                  associated with <a>payment handler</a>.
Should this say for the permission associated with `<a>payment handler's</a> <a>origin</a>`?

2017-06-21 16:55 UTC, romandev reviewed
@rsolomakhin, @dlongley 

Thank you for review 👍 

I addressed your comments.

2017-06-21 16:55 UTC, romandev commented on index.html
> +        [Exposed=Window] static Promise&lt;PermisionState&gt; requestPermission();
Done.

FYI, I found a history of Notification.requestPermission().
https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Jul/0178.html

2017-06-21 16:55 UTC, romandev commented on index.html
> +            <a>Promise</a> rejected with a <a>SecurityError</a>.
Done.

2017-06-21 16:55 UTC, romandev commented on index.html
> +            <a>Promise</a> rejected with a <a>SecurityError</a>.
Done.

2017-06-21 16:55 UTC, romandev commented on index.html
> +                  associated with <a>payment handler</a>.
Done.

2017-06-21 16:55 UTC, romandev commented on index.html
> +                "granted", and "denied" otherwise.
In the implementation, I defined PaymentHandlerStatus as 'default' instead of 'prompt'.
Because the Notification spec[1] is doing like that.
But I awared that we can use PermissionState in Permission API spec[2] instead of our own definition.

[1] https://notifications.spec.whatwg.org/#enumdef-notificationpermission
[2] https://www.w3.org/TR/permissions/#idl-def-PermissionState

2017-06-21 17:28 UTC, ianbjacobs commented on index.html
> +        [Exposed=Window] static Promise&lt;PermisionState&gt; requestPermission();
Thanks @romandev, @rsolomakhin, and @dlongley!

@romandev, you deleted:
  " The user agent is NOT REQUIRED to prompt the user to grant  permission to the origin for each new supported payment method."

I think we still need that text.

2017-06-21 17:42 UTC, romandev commented on index.html
> +        [Exposed=Window] static Promise&lt;PermisionState&gt; requestPermission();
@ianbjacobs, You're correct!

Done. Thanks.

2017-06-21 17:44 UTC, ianbjacobs commented
Thanks @romandev! @rsolomakhin if you are satisfied your comments have been addressed, please give the green light to merge.

2017-06-21 17:44 UTC, rsolomakhin approved these changes

2017-06-22 07:28 UTC, adrianhopebailie requested changes

2017-06-22 07:28 UTC, adrianhopebailie commented on index.html
> +            <li>Return <var>p</var>
Shouldn't we return the promise before we resolve it?

2017-06-22 07:48 UTC, romandev commented on index.html
> +            <li>Return <var>p</var>
@adrianhopebailie Thank you for review.

As far as I know, we are already using the pattern in many places in this spec or other specs. [1][2]
Resolving the promise will happen in parallel due to the following sentence:
"Run the following steps in parallel:"

So, I think it makes sense. WDYT?
(If I'm missing something, please correct me! :) )

[1] https://w3c.github.io/payment-handler/#has-method
[2] https://w3c.github.io/ServiceWorker/#cache-match

2017-06-22 14:53 UTC, adrianhopebailie commented on index.html
> +            <li>Return <var>p</var>
You are right, happy for you to merge as is. 

I find the pattern used in the Payment Request spec easier to follow. If you agree then perhaps we should change across the document in a new PR?

1. Let `p` be a new Promise
2. Return `p` and perform the remaining steps in parallel.

Example in https://www.w3.org/TR/payment-request/#show-method at step 9.

2017-06-22 14:53 UTC, adrianhopebailie approved these changes

2017-06-23 20:58 UTC, romandev commented on index.html
> +            <li>Return <var>p</var>
I'll do it in follow-up PR!
Could you merge this PR? I don't have a permission to merge.
Thank you!

2017-06-23 21:36 UTC, merged