Add AbortPaymentEvent.
w3c/webpayments-payment-apps-api pull request #207
Opened 2017-08-28 19:57 UTC by rsolomakhin

2017-08-29 14:24 UTC, rsolomakhin commented
Pease don't merge until I've reported on implementation experience.

2017-08-30 09:56 UTC, marcoscaceres commented
Made a "do not merge" label... to celebrate :)

2017-08-30 14:46 UTC, romandev commented
If CanMakePayment event is risky, AbortPayment event might also be risky?
Because it can be triggered from merchant's abort() call without user interaction.
The event doesn't take any information but it's not important.
Might take some informations such as urls by using clients.matchAll with includeUncontrolled option.

2017-08-30 15:03 UTC, rsolomakhin commented
The user agent fires the `AbortPayment` event only in the currently invoked payment app. From user perspective, that's after the user has selected a payment app and clicked [PAY], while the user is waiting for the payment app to complete. From implementation perspective, that's after `PaymentRequest` event has been fired, but before `PaymentRequest.updateWith()` promise has been resolved. At this point, the user has given explicit consent for the merchant website's information to be passed into the payment app to facilitate the payment. Hence, the risk of `AbortPayment` event is low.

2017-11-28 09:33 UTC, marcoscaceres requested changes
This is a good start. I think we can get Payment Request to do some of the work tho.

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +          The <a>paymentManager</a> attribute exposes payment handler
Shouldn't this be a `dfn`?

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +      <p>
This paragraph is redundant. This should be in an algorithm somewhere (probably is, just haven't gotten to it).

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +        a transaction or issue a refund. (This is out of scope.) The <a>payment
Note, this whole talk of "refunds" and other "money talk" is not ideal. We should only talk about how we manipulate things in the API - but not go into this kind of detail. We can describe "here is how you do a refund" in tutorial material.

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +        implementation will behave as if <a data-lt=
Nit: there is no need to use `data-lt` :) Just add `data-link-for="AbortPaymentEvent"` in a parent element (either the paragraph or the parent `<section>`).

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +            The <a>onabortpayment</a> attribute is an <a>event handler</a>
Nit: `<a>event handler</a>` should be `<a>event handler attribute</a>` and linked to HTML correctly.

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +            abortpayment.
`abortpayment` should be in quotes

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +          Upon <a data-cite=
Nit: we should try to be consistent with how we reference PaymentRequest.show/abort/etc. See the fix I made above, which gives you the nice linking both the PaymentRequest interface and the method itself..

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +          <a>PaymentRequestEvent</a> that is being processed.
Q: How are these linked together? Is there some more explicit means to get at the registration from the event?

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +          <li>If <var>registration</var> is not found, reject the
"not found" makes is sounds like some kind of lookup took place. Maybe we want:

 1. Let registration be (... steps to get the registration....)
 1. If registration is null, then...

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +          <a>Promise</a> that was created by <a data-cite=
So, I don't think we can do this... we need to hook back into Payment Request here - but we can't reach across threads and reject the promise?

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +            callbackSteps</var> set to the following steps:
Maybe we want some kinda of task here? This looks like a task.

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +            <ol>
Yeah, we shouldn't need to do any of this... Payment Request should do this for us. We just need to tell Payment Request that we have aborted, and it should do all this, no?

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +              <li>Wait for all of the promises in the <a>extend lifetime
This feels out of place to me. Shouldn't we get this for free from .waitUntil() without needing to say anything? Hopefully this whole task can go away.

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +              <a>DOMException</a> whose value "<a>OperationError</a>".
You can remove this whole thing. Payment Request doesn't know anything about "OperationError"s and WebIDL will just coerce anything you send into `.respondeWith()` into a boolean.

2017-11-28 09:33 UTC, marcoscaceres commented on index.html
> +              <a>DOMException</a> whose value "<a>OperationError</a>".
...anyway, I'm kinda sure this whole thing needs to go away. Fingers crossed!

2017-12-03 23:41 UTC, rsolomakhin commented on index.html
> +          The <a>paymentManager</a> attribute exposes payment handler
There's a <dfn> for paymentManager eight lines above. I'm not super familiar with spec format, but shouldn't there be a single <dfn> tag per term in a spec?

2017-12-03 23:44 UTC, rsolomakhin commented on index.html
> +        implementation will behave as if <a data-lt=
That's a neat trick, thank you!

2018-09-19 15:35 UTC, rsolomakhin commented
Let me close this pull request and submit a new one.

2018-09-19 15:36 UTC, closed without merging