Cross-origin iframes and feature policy.
w3c/webpayments-payment-apps-api pull request #282
Opened 2018-04-09 14:22 UTC by rsolomakhin

Prohibit cross-origin iframes from installing payment handlers, unless
allowed by the feature policy.

closes #281

The following tasks have been completed:

 * [ ] web platform tests
 * [ ] MDN Docs added

Implementation commitment:

 * [ ] Safari
 * [x] [Chrome](https://crbug.com/828948)
 * [ ] Firefox
 * [ ] Edge

***
<a href="https://pr-preview.s3.amazonaws.com/rsolomakhin/payment-handler/pull/282.html" title="Last updated on Sep 19, 2018, 6:53 PM GMT (eb1fb88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/282/697480d...rsolomakhin:eb1fb88.html" title="Last updated on Sep 19, 2018, 6:53 PM GMT (eb1fb88)">Diff</a>

2018-04-09 14:23 UTC, rsolomakhin commented
@marcoscaceres: Am I holding it right?

2018-04-14 02:49 UTC, ghost approved these changes

2018-04-16 04:52 UTC, marcoscaceres requested changes
Couple of nits, but generally looks great.

2018-04-16 04:52 UTC, marcoscaceres commented on index.html
> +          <li>Cross-origin iframes should not be able to register payment
"should not" doesn't read well here, as is "iframes". Perhaps just state that:

> The top-level document needs to explicitly grant access to nested browsing contexts via the "payment" feature policy. 

I've filed https://github.com/WICG/feature-policy/issues/154 so we can actually link to "payment".

2018-04-16 04:52 UTC, marcoscaceres commented on index.html
> +            <li>If the <a>document</a> is not <a>allowed to use</a> the
Nit: drop "policy-controlled-feature", it's redundant.

2018-04-16 04:52 UTC, marcoscaceres commented on index.html
> +            with <a>SecurityError</a>.
Here, you want:

```HTML
"<a>SecurityError</a>" <a>DOMException</a>.
```

You can take the `dfn`s from payment request.

2018-04-17 05:12 UTC, marcoscaceres commented on index.html
> +          <li>Cross-origin iframes should not be able to register payment
Fixed wording above.

2018-08-16 16:45 UTC, rsolomakhin commented
@marcoscaceres Please take another look! I've taken your suggestions.

2018-08-20 03:07 UTC, marcoscaceres commented
Generally, this looks good. 

Nit: I think you can probably drop all the "policy-controlled-feature"s throughout.

2018-09-19 18:53 UTC, rsolomakhin commented
@marcoscaceres: I've applied your fixes throughout. OK to merge?

2018-11-13 16:11 UTC, ianbjacobs commented
Hi @rsolomakhin ,

Are we ready to merge this pull request?

Ian

2018-11-13 17:32 UTC, rsolomakhin commented
@ianbjacobs: I'm ready to go, just need a review from @marcoscaceres, I think.

2018-11-14 06:17 UTC, marcoscaceres approved these changes

2018-11-14 06:18 UTC, marcoscaceres commented
So, editorially it looks fine. Any plans to finish the checklist above before merging tho? I assume there are tests already.

2018-11-14 06:21 UTC, marcoscaceres commented
I wonder if we should  get a second pair of eyes on the Feature Policy stuff before we merge? I don't know that spec very well, and having assurance from one of the editors of that spec that we've not missed anything might be good. Just a thought.

2018-11-14 14:57 UTC, rsolomakhin commented
I will work on more web platform tests eventually, but not this week. We can wait for more web platform tests from Chrome to land before merging this in.

2023-01-25 18:11 UTC, rsolomakhin commented
Now that PaymentInstruments API is removed, the only way to install a payment handler is during a transaction ("just-in-time") through `PaymentRequest.show()`, which already has the desirable properties with iframes and feature policy. Therefore, this pull request can be safely abandoned.

2023-01-25 18:11 UTC, closed without merging