Remove link to issue 157
w3c/webpayments-payment-apps-api pull request #292
Opened 2018-04-15 06:39 UTC by romandev

The issue 157 was already closed and it is making a respec error.

closes #157

2018-04-16 14:17 UTC, rsolomakhin commented
The note should stay in, but it does not have to link to issue #157. The reason for keeping the note is to inform the reader that the `CanMakePaymentEvent` is still under discussion.

2018-04-16 14:17 UTC, rsolomakhin requested changes

2018-04-16 14:17 UTC, rsolomakhin commented on index.html
> -        <div class="issue" data-number="157">
Make change to `<div class="note">` instead?

2018-04-17 03:13 UTC, marcoscaceres commented on index.html
> -        <div class="issue" data-number="157">
Notes should be things we plan to keep in the spec tho.

2018-09-19 18:55 UTC, ianbjacobs commented
Closing; subsumed by a different pull request

2018-09-19 18:55 UTC, closed without merging