Simplifying functional event handling
w3c/webpayments-payment-apps-api pull request #305
Opened 2018-06-21 15:44 UTC by jakearchibald

I've simplified event firing as part of https://github.com/w3c/ServiceWorker/pull/1199.

Don't merge this until https://github.com/w3c/ServiceWorker/pull/1199 merges, but you can review now.

2018-09-07 12:19 UTC, jakearchibald commented
This can merge now btw. Anyone more familiar with the spec able to handle the conflicts?

2018-09-07 14:59 UTC, rsolomakhin commented on index.html
> +              <dd>The [[\details]].<a>id</a> from the <a>PaymentRequest</a></dd>
Bad merge: please remove paymentRequestId from CanMakePaymentEvent.

2018-09-07 14:59 UTC, rsolomakhin commented on index.html
> +              <dt><a data-lt="PaymentRequestEvent.modifiers">modifiers</a>
Bad merge: please remove modifiers from CanMakePaymentEvent.

2018-09-07 15:00 UTC, rsolomakhin commented on index.html
> +              <dt><a data-lt="PaymentRequestEvent.total">total</a>
Bad merge: please remove total from CanMakePaymentEvent.

2018-09-07 15:00 UTC, rsolomakhin commented on index.html
> +              <dt><a data-lt=
Bad merge: please remove instrumentKey from CanMakePaymentEvent.

2018-09-07 15:02 UTC, rsolomakhin requested changes
Thank you for the pull request! Please remove the extra fields that I pointed out from CanMakePaymentEvent.

2018-09-19 19:01 UTC, rsolomakhin commented
@jakearchibald : Could you resolve conflicts so we can merge this, please? Thank you.

2018-09-19 19:01 UTC, rsolomakhin commented
(If you don't have time, we can do it.)

2018-09-20 03:20 UTC, jakearchibald commented
On travels right now. Gimmie a week 😄.

2018-09-20 03:21 UTC, marcoscaceres commented
> (If you don't have time, we can do it.)

We should do it. Let poor Jake have a holiday :)

2018-10-08 16:03 UTC, ianbjacobs commented
May be superseded by
https://github.com/w3c/payment-handler/pull/327

2018-10-17 19:04 UTC, ianbjacobs commented
Hi @jakearchibald, closing this pull request. Thank you for doing it. With Rouslan we made your changes with a newer version of the spec:
 https://github.com/w3c/payment-handler/pull/327#pullrequestreview-165783247

2018-10-17 19:04 UTC, closed without merging