Edited specification to remove notions of open/proprietary
w3c/webpayments-payment-apps-api pull request #70
Opened 2016-11-16 19:18 UTC by ianbjacobs

Issue 67 was about lack of definitions of proprietary and open;
https://github.com/w3c/webpayments-payment-apps-api/issues/67

Those terms were not necessary for the specification, so it was edited
to remove the concepts.

2016-11-17 04:17 UTC, adrianhopebailie requested changes
Some suggested changes.

2016-11-17 04:17 UTC, adrianhopebailie commented on index.html
> +<li> User choice of payment apps that support a given payment method will depend on the payment method. For example, there may only be one app authorized to support a payment method owned by a compan
Proposed:

> User choice of payment apps that support a given payment method will depend on the method and, specifically, if that method has a manifest that limits the apps that are allowed to process payment requests for that method.

2016-11-17 04:17 UTC, adrianhopebailie commented on index.html
> +<li>    Although decoupling relieves merchants of implementing some aspects of the checkout experience, one consequence is that they give up some degree of control. This was already the case for some
Propose:

> some portion of data collection to the browser or third party payment apps.

2016-11-17 04:17 UTC, adrianhopebailie commented on index.html
> +<li>        For a payment method with an associated origin, the user agent can do some (security) checks by comparing the origin of the payment method and the payment app.</li>
Propose:

> For a payment method with an associated origin, and in the absence of a manifest, the user agent can do some (security) checks by comparing the origin of the payment method and the payment app.

2016-11-17 04:17 UTC, adrianhopebailie commented on index.html
> +      <li>The user agent <span class='rfc2119'>SHOULD</span> display recommended payment apps and configuration to not display recommended payment apps.</li>
This sentence doesn't really make sense.

Propose:

> display recommended payment apps and **allow user** configuration to not display recommended payment apps

2016-11-17 04:29 UTC, ianbjacobs commented
@adrianhopebailie,

I liked your suggestions and pushed some updates as follows:
https://github.com/w3c/webpayments-payment-apps-api/pull/70/commits/50d5bb25534b78b6a69544b49797ab85d2133461

I don't think we should assume a manifest is the only mechanism here, so I've tweaked your suggestions to speak about payment method owner authorization (which, for example, might
be represented via a manifest file).

Ian

2016-11-17 08:11 UTC, adrianhopebailie commented
> I don't think we should assume a manifest is the only mechanism here, so I've tweaked your suggestions to speak about payment method owner authorization (which, for example, might
> be represented via a manifest file).

I think we should be explicit so that anything other than relationships between method and app managed by a manifest are outside our scope...

E.g.: Assuming there is some other mechanism for payment method X's owners to manage the relationship between their X and payment apps (like a special agreement with browser vendors that Y app is the preferred app for their payment method and Y and Z must never appear together).

If the behaviour that the browsers implement doesn't match what we have specified then they are not conforming to the spec. But, if the spec only defines behaviour for when a manifest is the source of the method/app relationship then they can implement these custom behaviours without being non-conforming.

2016-12-02 18:27 UTC, adrianhopebailie approved these changes

2016-12-02 18:30 UTC, merged